<?php
/**
 * Created by PhpStorm.
 * User: demon
 * Date: 26.05.2017
 * Time: 14:00
 */

namespace app\components;


use yii\base\Widget;

class BookWidget extends Widget
{
    public $modelBook;
    public $now;
public function init()
{
    parent::init(); // TODO: Change the autogenerated stub
    if($this->now===null){
        $this->now=false;
    }
    if($this->modelBook===null){
        return $this->modelBook="Ошибка нет записей в базе";
    }

}

public function run()
{
    $now=$this->now;
    $modelBook=$this->modelBook;
    return $this->render('book',compact('modelBook','now'));
}
}