<?php
/**
 * Created by PhpStorm.
 * User: demon
 * Date: 14.05.2017
 * Time: 10:48
 */

namespace app\components;
use app\models\category;
use app\models\Janri;
use yii\base\Widget;
class CategoryWidget extends Widget
{
    public function init()
    {
        parent::init(); // TODO: Change the autogenerated stub
    }


    public function run()
    {                   $categoryModel= category::getDb()->cache(function($category){

        return category::find()->indexBy('id')->asArray()->all();
    },CACH_TIME);

       return $this->render('category',compact('categoryModel'));
    }


//
//    public static function widCategor($arr){
//
//        foreach ($arr as $v) {
//                //where(['parent_id'=>$v['id']])->all()
//            $q=$v['id'];
//            //$con=Yii::$app->db();
//            $count=Yii::$app->db->createCommand("SELECT * FROM book WHERE parent_id=$q")->cache(CACH_TIME)->queryAll();
//            $count=count($count);
//                        @$a.= "<a href=" . Url::to(['site/about', 'id' => $v['id']]) . ">" . $v['name'] .
//                                "<span class=\"badge\">" .$count."</span></a><br><br>";
//                      //  echo $a;
//
//
//                }
//        return $a;
//
//    }
}