<?php
/**
 * Created by PhpStorm.
 * User: demon
 * Date: 26.05.2017
 * Time: 19:10
 */

namespace app\components;


use app\models\ChatForm;
use app\models\Coment;
use yii\base\Widget;

class ChatWidget extends Widget
{
        public function init()
        {
            parent::init(); // TODO: Change the autogenerated stub
        }
        public function run()
        {
            $model=new ChatForm();
            $modelChat=Coment::getDb()->cache(function($Coment){
                return Coment::find()->indexBy('id')->asArray()->limit(100)->all();
            },CACH_TIME_COMENT);

            return $this->render('chat',compact('model','modelChat'));
        }
}