<?php
/**
 * Created by PhpStorm.
 * User: demon
 * Date: 17.07.2017
 * Time: 12:20
 */

namespace app\components;


use app\models\User;
use yii\base\Widget;

class OnlainWidget extends Widget
{
   public function init()
   {
       parent::init(); // TODO: Change the autogenerated stub
   }

   public function run()
   {
       $time=time();

       $user=User::find()->select('login,onlain,dataEndEnter')->asArray()->all();
       return $this->render('onlain',compact('user'));

   }
}