<?php
/**
 * Created by PhpStorm.
 * User: demon
 * Date: 16.05.2017
 * Time: 20:25
 */

namespace app\components;
use app\models\PoiskForm;
use yii\base\Widget;
use yii;
class PoiskWidget extends Widget
{
public function init()
{
    parent::init(); // TODO: Change the autogenerated stub
}

public function run()
{   $modelform=new PoiskForm();

    return $this->render('poisk',compact('modelform'));
}
}